# -*- coding: utf-8 -*-
"""Projet2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7ZeXZ3PJEN3DgS2Jx4kenDTj57RSAHp
"""

import pandas as pd
import seaborn as sns
import requests
from io import BytesIO
import gzip

url = "https://datasets.imdbws.com/name.basics.tsv.gz"
df_name = pd.read_csv(url, sep="\t")

df_name